language: node_js
sudo: required
dist: trusty
node_js: lts/*
install:
  - npm install -g bower purescript pulp
script:
  - npm install
  - bower install --production
  - pulp build
  - bower install
  - pulp test
